/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\xbox.gltf 
Author: Laser Design (https://sketchfab.com/Laserdesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xbox-wireless-controller-3d-scan-data-a3279a520f2d4143863c118f50b23a2d
Title: Xbox Wireless Controller 3D Scan Data
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Xbox/xbox.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} position={[0, 27.13, 62.889]} rotation={[2.882, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Xbox/xbox.gltf')
