/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\gun1.gltf 
Author: Назар Окружко (https://sketchfab.com/Deduska_1947)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/under-development-ubergewehr-1961-84220e12a7cb423a8dc01aa4b315e3e8
Title: [Under development] Ubergewehr 1961
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/Gun1/gun1.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Material} skeleton={nodes.Object_7.skeleton} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Material} skeleton={nodes.Object_9.skeleton} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Material} skeleton={nodes.Object_11.skeleton} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Material} skeleton={nodes.Object_13.skeleton} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Material} skeleton={nodes.Object_15.skeleton} />
      <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Material} skeleton={nodes.Object_17.skeleton} />
      <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.ug_a} skeleton={nodes.Object_19.skeleton} />
      <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.ug_a} skeleton={nodes.Object_21.skeleton} />
      <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.Material} skeleton={nodes.Object_23.skeleton} />
      <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.Material} skeleton={nodes.Object_25.skeleton} />
    </group>
  )
}

useGLTF.preload('/Gun1/gun1.gltf')
