/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\tree.gltf 
Author: Kostas3D (https://sketchfab.com/Kostas3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-stylized-tree-free-3d-model-game-asset-0adf522a14634f4fab0252233ab5f48a
Title: Low-Poly Stylized Tree, FREE 3D Model game asset
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Tree/tree.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} rotation={[0, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Tree/tree.gltf')
